spring:
  application:
    name: HelloClient
  cloud:
    discovery:
      client:
        simple:
          instances:
            HelloServer:
              - uri: http://localhost:7111

server:
  port: 7211


endpoints:
  restart:
    enabled: true